{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0",
    "title": "\"Explore With Me\". Система рейтинга",
    "description": "Для работы с системой рейтинга событий проекта \\\"Explore With Me\\\" предлагается использовать следующий API.\n<br>\n<br>Описание дано для API v1.0.\n\nSome useful links:\n- [The \"Explore With Me\" repository](https://github.com/alekseyshiyanov/java-explore-with-me/tree/feature_rating_events)\n- [The source API definition for the \"Explore With Me\"](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
    "contact": {
      "email": "shiyanov.aleksey.a@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "likes",
      "description": "Оценка событий"
    },
    {
      "name": "ranking",
      "description": "Рейтинг событий"
    }
  ],
  "paths": {
    "/likes/event/{eventId}/users/{userId}": {
      "post": {
        "tags": [
          "likes"
        ],
        "summary": "Добавление пользователем новой оценки события",
        "description": "Добавление пользователем новой оценки события.<br><br>Ограничения:<br>- нельзя добавить оценку собственному событию (ожидается код 409)",
        "operationId": "evaluateEvent",
        "parameters": [
          {
            "name": "eventId",
            "description": "id события",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "userId",
            "description": "id текущего пользователя",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "grade",
            "description": "Оценка события",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "DISLIKE",
                "LIKE"
              ],
              "default": "DISLIKE"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LikesDto"
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Пользователь или событие не найдены",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "409": {
            "description": "Попытка поставить оценку собственному событию",
            "content": {
              "application/json": {
                "example": {
                  "status": "CONFLICT",
                  "reason": "Собственное событие",
                  "message": "Инициатор не может оценить свое событие",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }          }
        }
      },
      "patch": {
        "tags": [
          "likes"
        ],
        "summary": "Изменение пользователем существующей оценки события",
        "description": "Изменение пользователем существующей оценки события",
        "operationId": "updateEventEvaluate",
        "parameters": [
          {
            "name": "eventId",
            "description": "id события",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "userId",
            "description": "id текущего пользователя",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "grade",
            "description": "Оценка события",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "DISLIKE",
                "LIKE"
              ],
              "default": "DISLIKE"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LikesDto"
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Оценка события не найдена",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "likes"
        ],
        "summary": "Удаление пользователем существующей оценки события",
        "description": "Удаление пользователем существующей оценки события",
        "operationId": "deleteEventEvaluate",
        "parameters": [
          {
            "name": "eventId",
            "description": "id события",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "userId",
            "description": "id текущего пользователя",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Оценка удалена"
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Оценка события не найдена",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/likes/event/{eventId}": {
      "get": {
        "tags": [
          "likes"
        ],
        "summary": "Получение списка оценок для конкретного события",
        "description": "Получение списка оценок для конкретного события",
        "operationId": "getEventLikes",
        "parameters": [
          {
            "name": "eventId",
            "description": "id события",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "queryType",
            "in": "query",
            "description": "Фильтр событий по типу",
            "required": false,
            "schema": {
              "type": "string",
              "default": "ALL",
              "enum": [
                "ALL",
                "POSITIVE",
                "NEGATIVE"
              ]
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Количество оценок, которые нужно пропустить для формирования текущего набора",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "Количество оценок в наборе",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/LikesDto"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Событие с указанными параметрами не найдено",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/likes/users/{userId}": {
      "get": {
        "tags": [
          "likes"
        ],
        "summary": "Получение списка оценок, поставленных конкретным пользователем",
        "description": "Получение списка оценок, поставленных конкретным пользователем",
        "operationId": "getUserLikes",
        "parameters": [
          {
            "name": "userId",
            "description": "id пользователя",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "queryType",
            "in": "query",
            "description": "Фильтр событий по типу",
            "required": false,
            "schema": {
              "type": "string",
              "default": "ALL",
              "enum": [
                "ALL",
                "POSITIVE",
                "NEGATIVE"
              ]
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Количество оценок, которые нужно пропустить для формирования текущего набора",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "Количество оценок в наборе",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/LikesDto"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Пользователь с указанными параметрами не найден",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/ranking/event/{eventId}": {
      "get": {
        "tags": [
          "ranking"
        ],
        "summary": "Получение информации о рейтинге конкретного события",
        "description": "Получение информации о рейтинге конкретного события",
        "operationId": "getEventRanking",
        "parameters": [
          {
            "name": "eventId",
            "description": "id события",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RankingDto"
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Событие с указанными параметрами не найдено или еще не оценено",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    },
    "/ranking/event": {
      "get": {
        "tags": [
          "ranking"
        ],
        "summary": "Получение отсортированного списка оценок",
        "description": "",
        "operationId": "getSortedRanking",
        "parameters": [
          {
            "name": "sort",
            "in": "query",
            "description": "Тип сортировки",
            "required": false,
            "schema": {
              "type": "string",
              "default": "NONE",
              "enum": [
                "NONE",
                "RATING"
              ]
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Количество оценок, которые нужно пропустить для формирования текущего набора",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 0
            }
          },
          {
            "name": "size",
            "in": "query",
            "description": "Количество оценок в наборе",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32",
              "default": 10
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RankingDto"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Запрос составлен некорректно",
            "content": {
              "application/json": {
                "example": {
                  "status": "BAD_REQUEST",
                  "reason": "Incorrectly made request.",
                  "message": "Failed to convert value of type java.lang.String to required type long; nested exception is java.lang.NumberFormatException: For input string: ad",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          },
          "404": {
            "description": "Событие с указанными параметрами не найдено или еще не оценено",
            "content": {
              "application/json": {
                "example": {
                  "status": "NOT_FOUND",
                  "reason": "The required object was not found.",
                  "message": "Compilation with id=84 was not found",
                  "timestamp": "2022-09-07 09:10:50"
                },
                "schema": {
                  "$ref": "#/components/schemas/ApiError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiError": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "description": "Список стектрейсов или описания ошибок",
            "example": [],
            "items": {
              "type": "string",
              "description": "Список стектрейсов или описания ошибок",
              "example": "[]"
            }
          },
          "message": {
            "type": "string",
            "description": "Сообщение об ошибке",
            "example": "Only pending or canceled events can be changed"
          },
          "reason": {
            "type": "string",
            "description": "Общее описание причины ошибки",
            "example": "For the requested operation the conditions are not met."
          },
          "status": {
            "type": "string",
            "description": "Код статуса HTTP-ответа",
            "example": "FORBIDDEN",
            "enum": [
              "100 CONTINUE",
              "101 SWITCHING_PROTOCOLS",
              "102 PROCESSING",
              "103 CHECKPOINT",
              "200 OK",
              "201 CREATED",
              "202 ACCEPTED",
              "203 NON_AUTHORITATIVE_INFORMATION",
              "204 NO_CONTENT",
              "205 RESET_CONTENT",
              "206 PARTIAL_CONTENT",
              "207 MULTI_STATUS",
              "208 ALREADY_REPORTED",
              "226 IM_USED",
              "300 MULTIPLE_CHOICES",
              "301 MOVED_PERMANENTLY",
              "302 FOUND",
              "302 MOVED_TEMPORARILY",
              "303 SEE_OTHER",
              "304 NOT_MODIFIED",
              "305 USE_PROXY",
              "307 TEMPORARY_REDIRECT",
              "308 PERMANENT_REDIRECT",
              "400 BAD_REQUEST",
              "401 UNAUTHORIZED",
              "402 PAYMENT_REQUIRED",
              "403 FORBIDDEN",
              "404 NOT_FOUND",
              "405 METHOD_NOT_ALLOWED",
              "406 NOT_ACCEPTABLE",
              "407 PROXY_AUTHENTICATION_REQUIRED",
              "408 REQUEST_TIMEOUT",
              "409 CONFLICT",
              "410 GONE",
              "411 LENGTH_REQUIRED",
              "412 PRECONDITION_FAILED",
              "413 PAYLOAD_TOO_LARGE",
              "413 REQUEST_ENTITY_TOO_LARGE",
              "414 URI_TOO_LONG",
              "414 REQUEST_URI_TOO_LONG",
              "415 UNSUPPORTED_MEDIA_TYPE",
              "416 REQUESTED_RANGE_NOT_SATISFIABLE",
              "417 EXPECTATION_FAILED",
              "418 I_AM_A_TEAPOT",
              "419 INSUFFICIENT_SPACE_ON_RESOURCE",
              "420 METHOD_FAILURE",
              "421 DESTINATION_LOCKED",
              "422 UNPROCESSABLE_ENTITY",
              "423 LOCKED",
              "424 FAILED_DEPENDENCY",
              "425 TOO_EARLY",
              "426 UPGRADE_REQUIRED",
              "428 PRECONDITION_REQUIRED",
              "429 TOO_MANY_REQUESTS",
              "431 REQUEST_HEADER_FIELDS_TOO_LARGE",
              "451 UNAVAILABLE_FOR_LEGAL_REASONS",
              "500 INTERNAL_SERVER_ERROR",
              "501 NOT_IMPLEMENTED",
              "502 BAD_GATEWAY",
              "503 SERVICE_UNAVAILABLE",
              "504 GATEWAY_TIMEOUT",
              "505 HTTP_VERSION_NOT_SUPPORTED",
              "506 VARIANT_ALSO_NEGOTIATES",
              "507 INSUFFICIENT_STORAGE",
              "508 LOOP_DETECTED",
              "509 BANDWIDTH_LIMIT_EXCEEDED",
              "510 NOT_EXTENDED",
              "511 NETWORK_AUTHENTICATION_REQUIRED"
            ]
          },
          "timestamp": {
            "type": "string",
            "description": "Дата и время когда произошла ошибка (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2022-06-09 06:27:23"
          }
        },
        "description": "Сведения об ошибке"
      },
      "LikesDto": {
        "type": "object",
        "description": "Описание оценки события",
        "required": [
          "id",
          "user",
          "event",
          "grade"
        ],
        "properties": {
          "id": {
            "description": "Идентификатор оценки события",
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "user": {
            "$ref": "#/components/schemas/UserShortDto"
          },
          "event": {
            "$ref": "#/components/schemas/EventShortDto"
          },
          "grade": {
            "type": "string",
            "description": "Оценка события",
            "enum": [
              "DISLIKE",
              "LIKE"
            ]
          }
        }
      },
      "EventShortDto": {
        "required": [
          "id",
          "annotation",
          "category",
          "confirmedRequests",
          "eventDate",
          "initiator",
          "paid",
          "title",
          "views"
        ],
        "type": "object",
        "properties": {
          "annotation": {
            "type": "string",
            "description": "Краткое описание",
            "example": "Эксклюзивность нашего шоу гарантирует привлечение максимальной зрительской аудитории"
          },
          "category": {
            "$ref": "#/components/schemas/CategoryDto"
          },
          "confirmedRequests": {
            "type": "integer",
            "description": "Количество одобренных заявок на участие в данном событии",
            "format": "int64",
            "example": 5
          },
          "eventDate": {
            "type": "string",
            "description": "Дата и время на которые намечено событие (в формате \"yyyy-MM-dd HH:mm:ss\")",
            "example": "2024-12-31 15:10:05"
          },
          "id": {
            "type": "integer",
            "description": "Идентификатор",
            "format": "int64",
            "example": 1
          },
          "initiator": {
            "$ref": "#/components/schemas/UserShortDto"
          },
          "paid": {
            "type": "boolean",
            "description": "Нужно ли оплачивать участие",
            "example": true
          },
          "title": {
            "type": "string",
            "description": "Заголовок",
            "example": "Знаменитое шоу 'Летающая кукуруза'"
          },
          "views": {
            "type": "integer",
            "description": "Количество просмотрев события",
            "format": "int64",
            "example": 999
          }
        },
        "description": "Краткая информация о событии"
      },
      "CategoryDto": {
        "description": "Категория",
        "required": [
          "id",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Идентификатор категории",
            "format": "int64",
            "readOnly": true,
            "example": 1
          },
          "name": {
            "maxLength": 50,
            "minLength": 1,
            "type": "string",
            "description": "Название категории",
            "example": "Концерты"
          }
        }
      },
      "UserShortDto": {
        "type": "object",
        "description": "Пользователь (краткая информация)",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "description": "Идентификатор пользователя",
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "name": {
            "description": "Имя пользователя",
            "type": "string",
            "example": "fehguy"
          }
        }
      },
      "RankingDto": {
        "type": "object",
        "description": "Информация о рейтинге события",
        "required": [
          "event",
          "ranking",
          "likes",
          "positive"
        ],
        "properties": {
          "event": {
            "$ref": "#/components/schemas/EventShortDto"
          },
          "ranking": {
            "description": "Рейтинг события",
            "type": "number",
            "format": "double",
            "example": 0.6587
          },
          "likes": {
            "description": "Количество поставленных оценок",
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "positive": {
            "description": "Количество положительных оценок",
            "type": "integer",
            "format": "int64",
            "example": 6
          }
        }
      }
    }
  }
}
